apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-blue
  labels:
    app: my-app
    harness.io/color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      harness.io/color: blue
  template:
    metadata:
      labels:
        app: my-app
        harness.io/color: blue
    spec:
      containers:
        - name: my-app
          image: "nasi101/tetris:v1"  # Blue Version
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: my-app
    harness.io/color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      harness.io/color: green
  template:
    metadata:
      labels:
        app: my-app
        harness.io/color: green
    spec:
      containers:
        - name: my-app
          image: "nasi101/tetris:v2"  # Green Version
          ports:
            - containerPort: 8080
