apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    version: stable
  annotations:
    harness.io/direct-apply: "true"  # Important for Harness Canary Deployment
spec:
  replicas: 3  # Primary replicas
  selector:
    matchLabels:
      app: my-nginx
      version: stable
  template:
    metadata:
      labels:
        app: my-nginx
        version: stable
    spec:
      containers:
      - name: nginx
        image: nginx:1.19  # Stable version
        ports:
        - containerPort: 80
