apiVersion: v1
kind: Service
metadata:
  name: my-app-service12  # Primary Service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
    harness.io/color: blue  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
