apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    harness.io/color: blue  # Change to "green" to switch traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
