apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
spec:
  selector:
    app: my-nginx  # Common label for both canary and stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
