apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  annotations:
    harness.io/primary-service: "true"  # Ensures Harness swaps traffic
spec:
  selector:
    app: my-app
    harness.io/color: blue  # This will be swapped to "green" automatically
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
