apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # No need to specify "blue" or "green" here
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
